// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvuugjsdizdhzucoglhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dXVnanNkaXpkaHp1Y29nbGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTA2NjEsImV4cCI6MjA2MTY4NjY2MX0.g7rTsD7oZTQhqr7J7ZHATrqZjw7-miRRKjAvJq-wSBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);